services:
  postgres:
    image: postgres:17
    container_name: webhooks_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=webhook_inspector
      